name: ${{ github.actor }}'s Very First GitHub Actions
run-name: I Love æ˜å¤ªå­ ğŸ£
on: [push]
jobs:
  Eat-Mentaiko:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ã“ã‚ŒãŒåƒ•ã®æœ€åˆã®GitHub Actionsã ã‚ã‚ã‚ï¼"
      - run: echo "ã‚‚ã†èª°ã«ã‚‚æ­¢ã‚ã‚‰ã‚Œãªã„ã›ï¼"
      - run: echo "ä»Šæ—¥ã¯æ˜å¤ªå­ã‚’é£Ÿã¹ã‚‹ã"
      - run: echo "ã“ã®ã‚¸ãƒ§ãƒ–ã®ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã¯ã€${{ job.status }}ã€‘ã ã‚ˆ"
